expression = 
    [ "+" | "-" ], term, { [ "+" | "-" ], term }
;

term =
    factor, { ( "**" | "*" | "/" | % ), factor }
;

factor = 
    number |
    variable |
    bracketed_expression |
    function_call
;

variable = 
    dotted_identifier
;

function_call = 
    dotted_identifier, "(", expression, ")"
;

bracketed_expression = 
    "(", expression, ")"
;

boolean_operator = 
    "=" | "<" | ">" | "<=" | ">="
;

dotted_identifier = 
    identifier, { ".", identifier }