export enum TokenType {
    Equals = <any>'=',
    Greater = <any>'>',
    GreaterOrEqual = <any>'>=',
    Less = <any>'<',
    LessOrEqual = <any>'<=',
    Comma = <any>',',
    Identifier = <any>'identifier',
    Plus = <any>'+',
    Slash = <any>'/',
    DoubleAsterisk = <any>'**',
    Percent = <any>'%',
    Asterisk = <any>'*',
    Minus = <any>'-',
    Number = <any>'number',
    ParenthesisClose = <any>')',
    ParenthesisOpen = <any>'(',
    Terminator = <any>'terminator',
}
